{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Under investigation",
      "package_name": "PackageKit",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Under investigation",
      "package_name": "PackageKit",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "PackageKit",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2020-09-24T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-16121 PackageKit: local attacker could use this issue to learn the MIME type of any file on the system",
    "id": "1884560",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1884560"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "2.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-200",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2020-16121",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": null
}