{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Not affected",
      "package_name": "bind",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Not affected",
      "package_name": "bind97",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "bind",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "bind",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "bind",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2020-08-20T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-8620 bind: A specially crafted large TCP payload can trigger an assertion failure in tcpdns.c",
    "id": "1869468",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1869468"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-400",
  "statement": "This version only affects bind-9.16.x. Therefore versions of bind package shipped with Red Hat Enterprise Linux are not affected by this flaw.",
  "acknowledgement": "Red Hat would like to thank ISC for reporting this issue. Upstream acknowledges Emanuel Almeida (Cisco Systems, Inc) as the original reporter.",
  "name": "CVE-2020-8620",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": [
    "https://kb.isc.org/docs/cve-2020-8620"
  ]
}