{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-25032"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An issue was discovered in Flask-CORS (aka CORS Middleware for Flask) before 3.0.9. It allows ../ directory traversal to access private resources because resource matching does not ensure that pathnames are in a canonical format."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/corydolphin/flask-cors/releases/tag/3.0.9",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/corydolphin/flask-cors/releases/tag/3.0.9"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-08-31T12:35Z",
  "publishedDate": "2020-08-31T04:15Z"
}