{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-13353"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "When importing repos via URL, one time use git credentials were persisted beyond the expected time window in Gitaly 1.79.0 or above. Affected versions are: \u003e=1.79.0, \u003c13.3.9,\u003e=13.4, \u003c13.4.5,\u003e=13.5, \u003c13.5.2."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13353.json",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13353.json"
        },
        {
          "name": "https://gitlab.com/gitlab-org/gitaly/-/issues/2882",
          "refsource": "MISC",
          "tags": [],
          "url": "https://gitlab.com/gitlab-org/gitaly/-/issues/2882"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-11-17T13:44Z",
  "publishedDate": "2020-11-17T01:15Z"
}