{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2019-14562"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Integer overflow in DxeImageVerificationHandler() EDK II may allow an authenticated user to potentially enable denial of service via local access."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://bugzilla.tianocore.org/show_bug.cgi?id=2215",
          "refsource": "MISC",
          "tags": [],
          "url": "https://bugzilla.tianocore.org/show_bug.cgi?id=2215"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-11-23T17:00Z",
  "publishedDate": "2020-11-23T16:15Z"
}