{
  "debianbug": 777079,
  "description": "Jython 2.2.1 uses the current umask to set the privileges of the class cache files, which allows local users to bypass intended access restrictions via unspecified vectors.",
  "releases": {
    "bullseye": {
      "fixed_version": "2.7.1+repack-1",
      "repositories": {
        "bullseye": "2.7.2+repack1-3"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "buster": {
      "fixed_version": "2.7.1+repack-1",
      "repositories": {
        "buster": "2.7.1+repack1-4~deb10u1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "sid": {
      "fixed_version": "2.7.1+repack-1",
      "repositories": {
        "sid": "2.7.2+repack1-3"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "stretch": {
      "nodsa": "Minor issue",
      "nodsa_reason": "ignored",
      "repositories": {
        "stretch": "2.5.3-16+deb9u1",
        "stretch-security": "2.5.3-16+deb9u1"
      },
      "status": "open",
      "urgency": "low"
    }
  },
  "scope": "local"
}